### ISSUE TITLE
Downloading attachment on signage requires read_baseinfrastructure perm instead of read_signage one

### ISSUE THREAD

**Issue by gutard** [GeotrekCE/Geotrek-admin#1403] opened 2015-03-11 09:41 UTC
The workaround is to grant "read_baseinfrastructure" in addition to "read_signage"

**Comment by gutard** [comment] 2015-03-11 10:48
Related to https://github.com/makinacorpus/django-paperclip/issues/13

**Comment by camillemonchicourt** [comment] 2015-03-11 10:52
Cant find this permission in the list... ???

**Comment by gutard** [comment] 2015-03-11 10:59
`read_baseinfrastructure` is an internal code name. In django admin, the complete name is `infrastructure | base infrastructure | Can read base infrastructure`

**Comment by camillemonchicourt** [comment] 2015-03-11 11:01
Yes but I have nothing called "base infrastructure".

**Comment by gutard** [comment] 2015-03-11 11:33
Nothing ? You should at least have add, change and delete permissions on baseinfrastructure.

You can add the required permission by hand:

`INSERT INTO auth_permission(name, content_type_id, codename) VALUES ('Can read base infrastructure', (SELECT id from django_content_type where model='baseinfrastructure'), 'read_baseinfrastructure');`

**Comment by camillemonchicourt** [comment] 2015-03-11 11:51
Yes, I checked in auth_permission table and here is an excerpt for read permissions : 


268;"Can export Touristic event";76;"export_touristicevent"
212;"Can export Trail";22;"export_trail"
231;"Can export Trek";52;"export_trek"
219;"Can export Work management edge";43;"export_workmanagementedge"
194;"Can read attachments";63;"read_attachment"
218;"Can read Competence edge";42;"read_competenceedge"
272;"Can read FlatPage";79;"read_flatpage"
224;"Can read Infrastructure";24;"read_infrastructure"
228;"Can read Intervention";27;"read_intervention"
216;"Can read Land edge";41;"read_landedge"
196;"Can read log entry";6;"read_logentry"
209;"Can read Path";14;"read_path"
214;"Can read Physical edge";39;"read_physicaledge"
233;"Can read POI";61;"read_poi"
230;"Can read Project";33;"read_project"
208;"Can read Report";67;"read_report"
226;"Can read Signage";24;"read_signage"
222;"Can read Signage management edge";44;"read_signagemanagementedge"
266;"Can read Touristic content";73;"read_touristiccontent"
267;"Can read Touristic event";76;"read_touristicevent"
211;"Can read Trail";22;"read_trail"
232;"Can read Trek";52;"read_trek"
220;"Can read Work management edge";43;"read_workmanagementedge"

Maybe because I did no "make loaddata" at all when updating from 0.29.0 to 0.32.2 ?

**Comment by camillemonchicourt** [comment] 2015-04-08 13:34
Fixed in 0.33 ?

**Comment by babastienne** [comment] 2023-09-05 20:53
Can't reproduce in 2.100.1

**Closed by babastienne** 2023-09-05 20:53 UTC
Labels: 🐛 bug
