### ISSUE TITLE
Import of parsers throw SuspiciousFileOperation when an url is not an image

### ISSUE THREAD

**Issue by LePetitTim** [GeotrekCE/Geotrek-admin#3572] opened 2023-04-14 13:05 UTC
When an url is not an image. We can't find any name for this particular url when we want to create the attachment as an image file, it throws an error SuspiciousFileOperation.

We should use  an attachment link when it is possible.

**Comment by babastienne** [comment] 2024-01-04 19:06
Duplicate of #3545

**Closed by babastienne** 2024-01-04 19:06 UTC
Labels: 🐛 bug
