### ISSUE TITLE
LOGBOOK - Order by date

### ISSUE THREAD

**Issue by camillemonchicourt** [GeotrekCE/Geotrek-admin#1123] opened 2014-06-24 14:00 UTC
Nice tool.

But actually it is not possible to sort LOGBOOK entries by DATE as the field as this format "19 juin 2014 09:35:32 (5 jours)". 

Or at least DEFAULT ORDER by DATE DESC to see the most recent entries when you access the LOGBOOK.

**Comment by babastienne** [comment] 2023-09-05 18:07
Duplicate of https://github.com/GeotrekCE/Geotrek-admin/issues/1973

**Closed by babastienne** 2023-09-05 18:07 UTC
Labels: severity: minor, scope: mapentity, feature: must-have
